apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-pvc
  namespace: tailscale #since infra (vpn tunnel) 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi