name: Deploy to EC2 Kubernetes
on: 
  push: 
    branches: [main] #triggers when you push into main branch
jobs:
  deploy: 
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout repository #provide descriptive label for specific step
          uses: actions/checkout@v4 #call pre-defined resuable action

        - name: Setup SSH key 
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_KEY }}" | base64 --decode > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
        
        - name: Debug key
          run: |
            ssh-keygen -l -f ~/.ssh/id_rsa
        
        - name: Copy k8s files to EC2
          run: |
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r k8s/ ${{ secrets.EC2_NAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/
        
        - name: Deploy to k3s
          run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_NAME }}@${{ secrets.EC2_HOST }} "sudo k3s kubectl apply -f /home/ubuntu/k8s -R"
